using System;

namespace EfSchemaVisualizer.Core.Archive;

/// Per-provider file text for ScaffoldGenerator. Pure string templates — no Roslyn, no I/O.
public static class ScaffoldTemplates
{
    public static string Csproj(string projectName, ScaffoldProvider provider)
    {
        var packageName = ProviderPackageName(provider);
        return $$"""
            <Project Sdk="Microsoft.NET.Sdk">

              <PropertyGroup>
                <OutputType>Exe</OutputType>
                <TargetFramework>net10.0</TargetFramework>
                <Nullable>enable</Nullable>
                <RootNamespace>{{projectName}}</RootNamespace>
              </PropertyGroup>

              <ItemGroup>
                <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
                  <PrivateAssets>all</PrivateAssets>
                  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
                </PackageReference>
                <PackageReference Include="{{packageName}}" Version="10.0.0" />
              </ItemGroup>

              <ItemGroup>
                <None Update="appsettings.json">
                  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
                </None>
              </ItemGroup>

            </Project>
            """;
    }

    public static string AppSettings(string projectName, ScaffoldProvider provider)
    {
        var connectionString = ProviderConnectionString(projectName, provider);
        return $$"""
            {
              "ConnectionStrings": {
                "DefaultConnection": "{{connectionString}}"
              }
            }
            """;
    }

    public static string DbContextFactory(string projectName, ScaffoldProvider provider)
    {
        var useMethod = ProviderUseMethod(provider);
        return $$"""
            using System;
            using System.IO;
            using System.Text.Json;
            using Microsoft.EntityFrameworkCore;
            using Microsoft.EntityFrameworkCore.Design;

            namespace {{projectName}};

            public class AppDbContextFactory : IDesignTimeDbContextFactory<AppDbContext>
            {
                public AppDbContext CreateDbContext(string[] args)
                {
                    var json = File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "appsettings.json"));
                    using var document = JsonDocument.Parse(json);
                    var connectionString = document.RootElement
                        .GetProperty("ConnectionStrings")
                        .GetProperty("DefaultConnection")
                        .GetString();

                    var optionsBuilder = new DbContextOptionsBuilder<AppDbContext>();
                    optionsBuilder.{{useMethod}}(connectionString);

                    return new AppDbContext(optionsBuilder.Options);
                }
            }
            """;
    }

    public static string Program(string projectName)
    {
        return $$"""
            using {{projectName}};

            var context = new AppDbContextFactory().CreateDbContext(args);
            Console.WriteLine("AppDbContext ready. Run 'dotnet ef migrations add Init' to create your first migration.");
            """;
    }

    public static string Readme(string projectName)
    {
        return $$"""
            # {{projectName}}

            Generated by EF Schema Visualizer.

            ## Getting started

            1. `dotnet restore`
            2. `dotnet ef migrations add Init`
            3. `dotnet ef database update`

            Only the files needed to make this a runnable project were generated; entity classes,
            `OnModelCreating` configuration, and anything already present in an uploaded project were
            preserved as uploaded/edited.
            """;
    }

    private static string ProviderPackageName(ScaffoldProvider provider) => provider switch
    {
        ScaffoldProvider.SqlServer => "Microsoft.EntityFrameworkCore.SqlServer",
        ScaffoldProvider.PostgreSql => "Npgsql.EntityFrameworkCore.PostgreSQL",
        ScaffoldProvider.Sqlite => "Microsoft.EntityFrameworkCore.Sqlite",
        _ => throw new ArgumentOutOfRangeException(nameof(provider)),
    };

    private static string ProviderUseMethod(ScaffoldProvider provider) => provider switch
    {
        ScaffoldProvider.SqlServer => "UseSqlServer",
        ScaffoldProvider.PostgreSql => "UseNpgsql",
        ScaffoldProvider.Sqlite => "UseSqlite",
        _ => throw new ArgumentOutOfRangeException(nameof(provider)),
    };

    private static string ProviderConnectionString(string projectName, ScaffoldProvider provider) => provider switch
    {
        ScaffoldProvider.SqlServer => $"Server=.;Database={projectName};Trusted_Connection=True;TrustServerCertificate=True",
        ScaffoldProvider.PostgreSql => $"Host=localhost;Database={projectName};Username=postgres;Password=postgres",
        ScaffoldProvider.Sqlite => $"Data Source={projectName}.db",
        _ => throw new ArgumentOutOfRangeException(nameof(provider)),
    };
}
